from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


Mood = Literal["happy", "sad", "chill", "energetic", "dramatic"]
Complexity = Literal["simple", "medium", "rich"]
SectionType = Literal["Intro", "Verse", "Chorus", "Bridge", "Outro"]


class MelodySection(BaseModel):
    name: str = Field(..., description="Section display name")
    section_type: SectionType = "Verse"
    midi_path: str = Field(..., description="Path to melody midi generated by recognizer")


class ArrangeRequest(BaseModel):
    bpm: int = Field(default=100, ge=60, le=200)
    key_root: str = "C"
    mode: Literal["major", "minor"] = "major"
    complexity: Complexity = "medium"
    tracks: list[str] = ["Piano Chords", "Bass", "Drums", "Pad"]
    sections: list[MelodySection]


class RecognizeResult(BaseModel):
    name: str
    bpm: int
    key_root: str
    mode: str
    midi_path: str
    note_count: int
    note_preview: list[str]


class ArrangeResult(BaseModel):
    arrangement_midi: str
    section_midis: list[str]
    tracks: list[str]
